version: "3"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=testdb
    ports:
      - "54321:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=vjeurkar03@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - ./pgadmin:/var/lib/pgadmin
  # docker run -p 8025:8025 -p 1025:1025 mailhog/mailhog
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    command:
      - "start-dev"
    depends_on:
      - postgres
    volumes:
      - ./kc-conf:/opt/keycloak/conf/

      