version: "3"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=testdb
    ports:
      - "54321:54321"
    volumes:
      - ./data:/var/lib/postgresql/data