version: "3"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=testdb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data