version: '3'

services:
  mysqldb:
    image: mysql/mysql-server:latest
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "admin"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST="mysqldb"
      - PMA_PORT="3306"
      - PMA_USER="root"
      - PMA_PASSWORD="admin"
      - MAX_EXECUTION_TIME=0
      - UPLOAD_LIMIT=256M
    depends_on:
      - mysqldb
