version: '3'

services:
  db:
    image: mysql/mysql-server:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "admin"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST="db"
      - PMA_PORT="3306"
      - PMA_USER="root"
      - PMA_PASSWORD="admin"
    # depends_on:
      # - db
