version: "3"

services:
  db:
    image: mysql/mysql-server:latest
    ports:
      - "3306:3306"
    environment:
      # Details : https://dev.mysql.com/doc/mysql-installation-excerpt/5.7/en/docker-mysql-more-topics.html#docker_var_mysql_database

      # To reset default root password
      MYSQL_ROOT_PASSWORD: "admin"

      # To allow mysql connection from outside of this docker. It can be from host sytem or another docker container.
      MYSQL_ROOT_HOST: "%"

      # User is created if not exists already.
      MYSQL_USER: "testuser"
      MYSQL_PASSWORD: "admin"
      
      # Database to be created while starting docker container. Requires MYSQL_USER and MYSQL_PASSWORD to be set.
      MYSQL_DATABASE: "testdb"
    volumes:
      # To persist databases created inside the container.
      - ./data:/var/lib/mysql
  grafana:
    image: grafana/grafana-oss:8.2.3
    ports:
      - "3000:3000"
    depends_on:
      - db