version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - ./data:/data
  commander:
    build: .
    depends_on:
      - redis
    ports:
      - 8080:80
    environment:
      - name=value
    # command: redis-commander --redis-port 6379 --redis-host redis --redis-password eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81 --redis-db testdb
    
    